# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5

#exec-once = mpvpaper -o "loop" '*' /home/phant0m/Videos/wavy-grass-moewalls-com.mp4
#exec-once = pkill swww || true && mpvpaper -o "--loop --hwdec=auto" -l bottom '*' /home/phant0m/Videos/wavy-grass-moewalls-com.mp4
