# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
#windowrulev2 = opacity 0.89 override 0.89 override, class:.*

# Disable blur for all xwayland apps
# windowrulev2 = noblur, xwayland:1

#windowrulev2 = opacity 0.82 0.71, class:^(kitty)$
#layerrule = blur, kitty

#windowrulev2 = opacity 0.94 0.91, class:^(code)$
#layerrule = blur, code

#windowrulev2 = opacity 0.91 0.80, class:^(discord)$
#layerrule = blur, discord

#windowrulev2 = opacity 0.91 0.80, class:^(spotify)$
#layerrule = blur, spotify

#windowrulev2 = opacity 0.95 0.85, class:^(org.telegram.desktop)$
#layerrule = blur, org.telegram.desktop

#windowrulev2 = opacity 0.95 0.85, class:^(org.kde.dolphin)$
#layerrule = blur, dolphin

windowrule = opacity 0.82 0.70, match:class kitty
windowrule = opacity 0.90 0.80, match:class code
windowrule = opacity 0.90 0.80, match:class discord
windowrule = opacity 0.90 0.80, match:class spotify
windowrule = opacity 0.90 0.80, match:class org.telegram.desktop
windowrule = opacity 0.90 0.80, match:class org.kde.dolphin
windowrule = opacity 0.82 0.70, match:class org.kde.konsole
windowrule = opacity 0.70 0.55, match:class org.nickvision.cavalier
